version: 0.2

phases:
  install:
    runtime-versions:
        docker: 18
        dotnet: 2.2
  pre_build:
    commands:
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t 520384133655.dkr.ecr.us-west-1.amazonaws.com/polarcloud-web:latest .
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push 520384133655.dkr.ecr.us-west-1.amazonaws.com/polarcloud-web:latest