version: 1

phases:
  install:
    runtime-versions:
        docker: 18
        dotnet: 3.1
  pre_build:
    commands:
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t 176275134597.dkr.ecr.us-west-1.amazonaws.com/idkpopup-website:latest .
  post_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-west-1)
      - docker push 176275134597.dkr.ecr.us-west-1.amazonaws.com/idkpopup-website:latest  